export const FETCH_CARDS = 'FETCH_CARDS';

export const REMOVE_SELECTED_CARDS = 'REMOVE_SELECTED_CARDS';

export const SAVE_CARD_HANDLER = 'SAVE_CARD_HANDLER';

export const SELECT_CARD_HANDLER = 'SELECT_CARD_HANDLER';

export const EDIT_CARD_HANDLER = 'EDIT_CARD_HANDLER';
